spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dbsemillero
    username: root
    password: 123456789
    driver-class-name: com.mysql.cj.jdbc.Driver
    spring:
      jpa:
        show-sql=true:

        spring:
          jackson:
            default-property-inclusion=non_null:

